package Entities;
// Generated Nov 21, 2012 10:42:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nome;
     private String sobrenome;
     private String email;
     private String login;
     private String senha;
     private boolean ativo;

    public Usuario() {
    }

	
    public Usuario(int id, String nome, String sobrenome, String login, String senha, boolean ativo) {
        this.id = id;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.login = login;
        this.senha = senha;
        this.ativo = ativo;
    }
    public Usuario(int id, String nome, String sobrenome, String email, String login, String senha, boolean ativo) {
       this.id = id;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.email = email;
       this.login = login;
       this.senha = senha;
       this.ativo = ativo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


